### ISSUE TITLE
Browser.dart: File output types

### ISSUE THREAD

**Issue by matanlurey** [matanlurey/svg#2]
Given a collection of parsed SVGs, there a few formats that would be nice to be emittable:
- [ ] PODO with getters/setters

``` dart
class CachedSvgData {
  // Strongly typed access (preferred for performance).
  final checkbox = const <SvgPathSegment> [
    const SvgPathSegment(...)
  ];

  // Dynamic access (easier for meta programming, integration with Angular, etc)
  List<SvgPathSegment> operator[](String key) {
    switch (key) {
      case 'checkbox': return checkbox;
    }
  }
}
```
- [ ] A font library and cooresponding SCSS to access the icons

``` scss
.cached-svg-data {
  font-family: 'CachedSvgDataCustomFont';
  &:before {
    &.checkbox { content: 'c'; }
  }
}
```
